config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/' => 'project#home', as: :root
  get '/about' => 'project#about', as: :about

  resources :stats, only: [:new, :index, :create]
  resources :users, only: [:new, :create]
  # resources :recipes
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  get '/guest_signin' => 'sessions#guest', as: :guest_signin

  resources :recipes, only: [:show, :index] do
    resources :foodlogs, only: [:create]
  end
  resources :foodlogs, only: [:destroy, :edit]
  get '/view_foodlogs' => 'foodlogs#show', as: :show_foodlog

  get '/auth/fitbit', as: :auth_fitbit
  post '/auth/fitbit' => 'callbacks#make_request', as: :fitbit_auth
  get '/auth/fitbit/callback' => 'callbacks#get_response'
  get '/weight' => 'callbacks#get_weight', as: :weight
  get '/add_weight' => 'callbacks#post_weight'

  namespace :api, defaults: {format: :json} do
      namespace :v1 do
        post '/authenticate_user' => 'users#login'
        post '/add_recipe' => 'recipes#add_recipe'
        get '/foodlogs' => 'recipes#show_foodlog'
        delete '/foodlogs' => 'recipes#delete_foodlog'
        get '/stats' => 'recipes#get_stats'
        resources :recipes, only: [:index]
      end
    end

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :foodlogs, dependent: :nullify
end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < Api::BaseController

  protect_from_forgery with: :null_session
  before_action :current_api_user, only: [:add_recipe, :show_foodlog, :delete_foodlog, :get_stats]

  def index
    recipes = Recipe.all
    render json: recipes
  end

  def show_foodlog
    @foodlogs = @current_api_user.foodlogs.where('created_at >= ?', Time.zone.now.beginning_of_day)
  end

  def delete_foodlog
    foodlog = Foodlog.find params[:foodlogId]
    if foodlog.destroy
      @foodlogs = @current_api_user.foodlogs.where('created_at >= ?', Time.zone.now.beginning_of_day)
    else
      render json: {success: false}
    end
  end

  def add_recipe
    foodlog = Foodlog.new recipe_params
    foodlog.user = @current_api_user
    if foodlog.save
      @foodlogs = @current_api_user.foodlogs.where('created_at >= ?', Time.zone.now.beginning_of_day)
    else
      render json: {success: false}
    end
  end

  def get_stats
    stats = @current_api_user.stats.last
    render json: stats
  end

  private

  def recipe_params
    params.require(:recipe).permit(:servings, :recipe_id)
  end

  def current_api_user
    @current_api_user = User.find_by_api_key request.headers["HTTP_API_KEY"]
  end


end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show]

  def index
    respond_to do |format|
      if current_user.stats.last.present?
        @recipes = Recipe.all
        @foodlog = current_user.foodlogs.where('created_at >= ?', Time.zone.now.beginning_of_day)
        @calorie_limit = current_user.stats.last.calories
        @calories = daily_calories
        @carbs = carbs_calories
        @fats = fats_calories
        @proteins = proteins_calories
        @total = 1 + @carbs + @fats + @proteins
        format.html { render }
        format.json { render json: @recipes }
      else
        format.html { redirect_to new_stat_path, alert: 'You must enter your stats first to use the meal planner' }
      end
    end
  end

  def show
    respond_to do |format|
      format.js { render 'showRecipeModal' }
    end
  end

  def new
    @recipe = Recipe.new
  end

  def edit
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:name, :ingredients, :calories, :servings, :fats, :carbs, :proteins, :tag, :photo, :directions)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(recipe) do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :ingredients %>
    <%= f.text_area :ingredients %>
  </div>

  <div class="field">
    <%= f.label :calories %>
    <%= f.number_field :calories %>
  </div>

  <div class="field">
    <%= f.label :servings %>
    <%= f.number_field :servings %>
  </div>

  <div class="field">
    <%= f.label :fats %>
    <%= f.text_field :fats %>
  </div>

  <div class="field">
    <%= f.label :carbs %>
    <%= f.text_field :carbs %>
  </div>

  <div class="field">
    <%= f.label :proteins %>
    <%= f.text_field :proteins %>
  </div>

  <div class="field">
    <%= f.label :tag %>
    <%= f.text_field :tag %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <%= f.text_field :photo %>
  </div>

  <div class="field">
    <%= f.label :directions %>
    <%= f.text_area :directions %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/_nutrition-information.html.erb
<section class="nutrition-facts">
  <header class="nutrition-facts_header">
    <h1 class="nutrition-facts_title">Nutrition Facts</h1>
    <p>Makes <%= @recipe.servings %> servings</p>
  </header>
  <table class="nutrition-facts__table">
    <thead>
      <tr>
        <th colspan="3" class="">
          <%= @recipe.calories %> Calories Per Serving
        </th>
      </tr>
    </thead>
    <tbody>

    <tr>
      <th colspan="2">
        <b>Total Fat</b>
      </th>
      <td>
        <b><%= @recipe.fats.to_i %>g</b>
      </td>
    </tr>
      <th colspan="2">
        <b>Total Carbohydrate</b>
      </th>
      <td>
        <b><%= @recipe.carbs.to_i %>g</b>
      </td>
    </tr>

    <tr class="thick-end">
      <th colspan="2">
        <b>Protein</b>
      </th>
      <td>
        <b><%= @recipe.proteins.round.to_i %>g</b>
      </td>
    </tr>
  </tbody>
</table>
</section>

app/views/recipes/_progress.html.erb
<div class="row">

  <div class="col-sm-9">
    <h3 style="margin: 10px 0 0 0">Today's Calorie Goals: <span id="calorie-display"><%= @calories %></span>/<span id="calorie-limit"><%= @calorie_limit %></span></h3>
    <div class="progress">
      <div id="calorie-bar" class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40"
      aria-valuemin="0" aria-valuemax="100" style="width:<%= (@calories * 100 / @calorie_limit).round(1) %>%; line-height: 30px">
        <%= (@calories * 100 / @calorie_limit  ).round(1) %>%
      </div>
    </div>

  </div>
  <div class="col-sm-3">
    <div class="col-xs-7" style="padding: 0">
      <h5>Calorie Composition:</h5>
      <div>
        <h5>Fats: <span id="fats-display"><%= (@fats / @total * 100).round(1) %>%</span><div class="macro-label" id="fats-color"></div></h5>
      </div>
      <div>
        <h5>Carbs: <span id="carbs-display"><%= (@carbs / @total * 100).round(1) %>%</span><div class="macro-label" id="carbs-color"></div></h5>
      </div>
      <div>
        <h5>Proteins:
          <span id="proteins-display">
            <% if @total == 1 %>
            0.0%
            <% else %>
            <%= ((@total - @fats - @carbs) / @total * 100).round(1) %>%
            <% end %>
        </span><div class="macro-label" id="proteins-color"></div></h5>
      </div>
    </div>
    <div class="col-xs-5" id="chart_area" style="padding: 0">
      <canvas id="macros_chart" height="300px"></canvas>
    </div>
  </div>
</div>

app/views/recipes/_show_modal.erb
<!-- Food Log Modal -->
<div class="modal fade" id="foodLogModal" tabindex="1" role="dialog" aria-labelledby="myModalLabel" style="width: 100%">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="width: 700px; height: 550px">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Recipe?</h4>
        <!-- <h6>You still have 2000 calories left today</h6> -->
      </div>
      <div class="modal-body">
        <% if @recipe %>
          <%= form_tag recipe_foodlogs_path(@recipe), remote: true do %>
            <div class="recipe-info row">
              <h3><%= @recipe.name %></h3>
              <div class="col-xs-4">
                <%= render 'nutrition-information' %>
              </div>
              <div class="col-xs-8">
                <img src="<%= @recipe.photo %>" alt="" style="width: 350px; height: 233px"/>
              </div>
            </div>
            <div class="">
              <h3>I want to make <%= text_field_tag :servings, "", value: "1", class: "servings-input",:required => true %> servings.</h3>
            </div>
            <hr style="margin: 15px 0">
            <%= submit_tag "Add Recipe To Today's Meal Plan", class: "btn btn-primary log-in-button", id: "modal-submit-btn"%>
            <span class="btn btn-primary" data-dismiss="modal" data-toggle="modal">On Second Thought..</span>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div>

  <h1 style="color: white">Add a recipe!</h1>
  <div id="photo-container" class="scrolling">
    <div class="photobanner">
      <% @recipes.each do |recipe| %>
        <%= link_to image_tag(recipe.photo, class: "recipe-photo"), recipe_path(recipe), remote: true, class: "recipe-link", id: recipe.id %>
      <% end %>
    </div>

    <div class="alert">
      <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
      Adding this recipe will exceed your daily allowance by <span id='excess-calories'></span> calories. Please choose something else.
    </div>
  </div>

  <div id="plan-area" class="row" >
    <h1>Today's Meals</h1>
    <div id="meals">
      <% if @foodlog %>
        <% @foodlog.each do |meal| %>
          <%= render 'foodlogs/foodlog', meal: meal %>
        <% end %>
      <% end %>
    </div>
  </div>

</div>

<div id="showFoodLogModal">
  <%= render "show_modal" %>
</div>

<div class="daily-progress">
  <%= render 'progress' %>
</div>

app/views/recipes/showRecipeModal.js.erb
$("#showFoodLogModal").html("<%= j(render('show_modal')) %>");
$("#foodLogModal").modal('show');

app/views/recipes/show_modal.js.erb
$("#showFoodLogModal").html("<%= j(render('show_modal')) %>");
$("#foodLogModal").modal('show');