config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/' => 'project#home', as: :root
  get '/about' => 'project#about', as: :about

  resources :stats, only: [:new, :index, :create]
  resources :users, only: [:new, :create]
  # resources :recipes
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  get '/guest_signin' => 'sessions#guest', as: :guest_signin

  resources :recipes, only: [:show, :index] do
    resources :foodlogs, only: [:create]
  end
  resources :foodlogs, only: [:destroy, :edit]
  get '/view_foodlogs' => 'foodlogs#show', as: :show_foodlog

  get '/auth/fitbit', as: :auth_fitbit
  post '/auth/fitbit' => 'callbacks#make_request', as: :fitbit_auth
  get '/auth/fitbit/callback' => 'callbacks#get_response'
  get '/weight' => 'callbacks#get_weight', as: :weight
  get '/add_weight' => 'callbacks#post_weight'

  namespace :api, defaults: {format: :json} do
      namespace :v1 do
        post '/authenticate_user' => 'users#login'
        post '/add_recipe' => 'recipes#add_recipe'
        get '/foodlogs' => 'recipes#show_foodlog'
        delete '/foodlogs' => 'recipes#delete_foodlog'
        get '/stats' => 'recipes#get_stats'
        resources :recipes, only: [:index]
      end
    end

end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  layout 'homepage_nav', only: :home

  def home
  end

  def about
  end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/project/_movingNav.html.erb
<!-- <div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#moving-navbar" aria-expanded="false" aria-controls="navbar">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="#">Project name</a>
</div> -->

<nav id="moving-navbar" class="navbar navbar-inverse test-header ">
  <ul class="nav navbar-nav moving-nav">
    <li class="pull-right">
      <a href="#" style="padding-bottom: 0; background: none" class="dropdown-toggle moving-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=  user_signed_in? ? "#{current_user.full_name.upcase}" : "PROFILE" %><span class="caret"></span></a>
      <ul class="dropdown-menu">
        <% if user_signed_in? %>
        <li><%= link_to "My Profile", new_stat_path %></li>
        <li><%= link_to "Sign Out", sessions_path, method: :delete %></li>
        <% else %>
        <li class="">
          <a type="button" data-toggle="modal" data-target="#LogInModal">
            Log In
          </a></li>
        <li class="">
          <a type="button" data-toggle="modal" data-target="#SignUpModal">
            Sign Up
          </a></li>
        <% end %>
      </ul>
    </li>
    <li class="pull-right"><a href="/recipes" style="padding-bottom: 0"class="moving-link">MEAL PLANNER</a></li>
    <li class="pull-right"><a href="#" style="padding-bottom: 0"class="moving-link">ABOUT</a></li>
    <li class="pull-right"><a href="#" style="padding-bottom: 0" class="moving-link">HOME</a></li>
  </ul>
</nav>

app/views/project/_signIn.html.erb
<!-- Log In Modal -->
<div class="modal fade" id="LogInModal" tabindex="1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Login to your account</h4>
        <h6>Enter your email and password to log on</h6>
      </div>
      <div class="modal-body sign-in-body">
        <%= form_tag sessions_path, remote: true do %>
          <!-- <div class=""> -->
            <div>
              <%= email_field_tag :email, nil, placeholder: "Email...", class: "log-in-input" %>
            </div>
            <div>
              <%= password_field_tag :password, nil, placeholder: "Password...", class: "log-in-input" %>
            </div>
            <div id="login-error"></div>
              <%= submit_tag "Log In", class: "btn btn-primary log-in-button" %>
            <% end %>
            <div style="text-align: center">
              <h5 style="margin: 0">or</h5>
            </div>
            <a href="/auth/fitbit" class="fitbit-button btn ">Log in with Fitbit
              <%= image_tag('fitbit.png', class: 'fitbit-logo')%>
            </a>
            <a href="#" id="forgot-password">Forgot Password?</a>
            <h5>Don't have an account?<a class="close" data-dismiss="modal" data-toggle="modal" data-target="#SignUpModal" id="link-to-sign-up">Sign Up</a></h5>

        </div>

    </div>
  </div>
</div>

app/views/project/_signUp.html.erb
<!-- Sign Up Modal -->
<div class="modal fade" id="SignUpModal" tabindex="1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog container" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign up to set up your profile</h4>
        <h6>Please enter your information below</h6>
      </div>
      <div class="modal-body sign-in-body" style="text-align: center">

        <% @user = User.new %>
        <%= @user.errors.full_messages.join(", ") %>

        <%= form_for @user do |f| %>
          <%= f.text_field :first_name, placeholder: "First Name...", class: "sign-up-input" %>
          <%= f.text_field :last_name, placeholder: "Last Name...", class: "sign-up-input" %>
          <%= f.email_field :email, placeholder: "Email...", class: "sign-up-input" %>
          <%= f.password_field :password, placeholder: "Password...", class: "sign-up-input" %>
          <%= f.password_field :password_confirmation, placeholder: "Confirm Password...", class: "sign-up-input" %>
        <%= f.submit "Sign Up", class: "btn btn-primary log-in-button" %>
          <h5 style="margin: 0">or</h5>
          <a href="/auth/fitbit" class="fitbit-button btn ">Sign up with Fitbit
            <%= image_tag('fitbit.png', class: 'fitbit-logo')%>
          </a>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/project/about.html.erb
<div class="container about-wrapper">
  <h1>About This App</h1>
  <div class="about-info">
    <h3 style="color: red">Disclaimer</h3>
    <h4 style="color: red">This website is meant to be a demonstration site ONLY. It was developed as the final project for our CodeCore Web Development bootcamp. All the recipes were pulled from user submitted posts from bodybuilding.com and muscleandstrength.com. As such, calorie and macronutrient accuracy of the recipes in this app are NOT guaranteed.</h4>
    <h3 class="about-section-title">What's the purpose of this app?</h3>
    <h4>We designed Eat Free to save you time and energy when it comes to weight loss. We have tools to calculate your personal calorie requirements depending on your desired weight loss rate. No more wondering what foods you can or cannot eat, by following the IIFYM (If It Fits Your Macros) strategy, you can eat whatever you want while losing weight! (Yes that includes junk food in moderate quantities)</h4>
    <h3 class="about-section-title">What is IIFYM?</h3>
    <h4><strong>If It Fits Your Macros</strong> is a diet strategy which the following approach: you can eat any foods you like, as long as it fits in your daily caloric budget and your daily macronutrient split (protein, carbohydrates, and fat). The gist of the idea is that if you eat oatmeal and whole wheat bread, the result (as far as body composition is concerned) is the same as if you were to eat the exact same amount of carbohydrates and fats from donuts, as long as calorie intake is equal and macronutrient targets are hit. According to this theory, gaining body fat is not about the types of foods you consume, rather the excess calories you are consuming.</h4>
    <h3 class="about-section-title">How does it work?</h3>
    <h4>By entering your physical stats the app will calculate your TDEE. Your TDEE (Total Daily Energy Expenditure) is an estimate of your maintenance level, that is, the amount of calories you must eat to maintain your current weight. From that as well as a desired weight loss rate that you specify, the app also calculates the maximum amount of calories you can consume per day to achieve said weight loss. From there the app provides a recipe list of various meals and snacks for you to build your meal plan from, ensuring that your daily calorie limit is not surpassed. A small lee-way of +50 calories is allowed provide ease of planning.</h4>

  </div>

  <h1>Frequently Asked Questions</h1>
  <div class="about-info">
    <h3 class="about-section-title">What are macros and why are they important?</h3>
    <h4>Macronutrients are what make up the caloric content of a food. Sometimes referred to as "macros" the three categories of macronutrients are carbohydrates, fat, and protein. The caloric combination of the macros is where the total number of calories comes from. In general, proteins and carbohydrates provide 4 calories per gram whereas fats provide 9 calories per gram. A good balance of macros is essential; a severe imbalance in any of the three macronutrients could lead to malnutrition and eventually long term health issues. </h4>
    <h3 class="about-section-title">How should I split my macros?</h3>
    <h4>There is no optimal macros split as everyone has different requirements. A professional athlete or bodybuilder will have significantly greater protein requirements than the average person with an interest in fitness. In addition, depending on what your goals are, (eg. weight loss, strength gains, mass gains, performance etc.) different splits may be more appropriate. That said, a well accepted starting place is the 40/40/20 split, a diet where 40% of your calories come from protein sources, 40% from carbohydrate sources and 20% from fat sources. The actual numbers can be adjusted over the course of the diet to meet your personal needs.</h4>
    <h3 class="about-section-title">How can I track my macros?</h3>
    <h4>Currently this app only tracks your macros composition on a day to day basis. Specifying a desired macros split and building meal plans that meet those macros is a feature that will be implemented in the future.</h4>
    <h3 class="about-section-title">How can the net amount of entropy of the universe be massively decreased?</h3>
    <h4>THERE IS INSUFFICIENT DATA FOR A MEANINGFUL ANSWER.</h4>
  </div>
</div>

app/views/project/home.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

<%= flash[:alert] %>
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag "jumbo1.jpg", class: "carousel-image" %>
    </div>
    <div class="item">
      <%= image_tag "jumbo2.jpg", class: "carousel-image" %>
    </div>
    <div class="item">
      <%= image_tag "jumbo3.jpg", class: "carousel-image" %>
    </div>
  </div>

  <div class="carousel-caption text apply-gradient">
    <div class="section-header section-boxed">
      <h1 id="main-title">Eat Free</h1>
      <nav class="navbar">
        <div class="header-wrapper" >
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myHomeNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse" id="myHomeNavbar">
          <ul class="nav navbar-nav container">
            <li class="home-link"><a href="/" class="link">HOME</a></li>
            <li class="home-link"><a href="/about" class="link">ABOUT</a></li>
            <!-- <li><a href="#" class="link">RECIPES</a></li> -->
            <% if user_signed_in? %>
              <li class="home-link"><%= link_to "MEAL PLANNER", recipes_path, class: "link" %></li>
            <% else %>
              <li class="home-link"><a type="button" data-toggle="modal" data-target="#LogInModal" class="link">MEAL PLANNER</a></li>
            <% end %>
            <li class="home-link">
              <a href="#" class="dropdown-toggle link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=  user_signed_in? ? "#{current_user.full_name.upcase}" : "PROFILE" %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if user_signed_in? %>
                <li><%= link_to "My Profile", new_stat_path %></li>
                <% if current_user.from_fitbit? %>
                  <li><%= link_to "Fitbit Data", stats_path, remote: true %></li>
                <% end %>
                  <li><%= link_to "View History", show_foodlog_path %></li>
                  <li><%= link_to "Sign Out", sessions_path, method: :delete %></li>
                <% else %>
                  <li>
                    <a type="button" data-toggle="modal" data-target="#LogInModal">
                      Log In
                    </a>
                  </li>
                  <li>
                    <a type="button" data-toggle="modal" data-target="#SignUpModal">
                      Sign Up
                    </a>
                  </li>
                  <li>
                    <%= link_to "Guest Login", guest_signin_path %>
                  </li>
                <% end %>
                </ul>
              </li>
            </ul>
          </div>
        </nav>

      </div>
    </div>

  </div>
</div>



<!-- <div id="image-wrapper">
  <div class="col-md-6 flip-image1" style="visibility: hidden" >
    <h2 class="flip-text"><span class="flip-text-span">Supplement your training with a tailored diet</span></h2>
  </div>

  <div class="col-md-6 flip-image2" style="visibility: hidden" >
    <h2 class="flip-text"><span class="flip-text-span">Take the guess work out of weight loss</span></h2>
  </div>
</div> -->

<!-- <div class="home-footer">
  <h3 style="margin: 0; padding: 4vmin">Connect with us.</h3>
  <div class="container" style="width: 60%">
    <div class="row" >
      <div class="col-xs-3">
          <div class="icon-border">
            <a href="#" class="icon-link">
              <div class="icon twitter">
              </div>
            </a>
          </div>
        <h6>FOLLOW ON TWITTER</h6>
      </div>
      <div class="col-xs-3">
        <div class="icon-border">
          <a href="#" class="icon-link">
            <div class="icon facebook">
            </div>
          </a>
        </div>
        <h6>LIKE ON FACEBOOK</h6>
      </div>
      <div class="col-xs-3">
        <div class="icon-border">
          <a href="#" class="icon-link">
            <div class="icon linkedin">
            </div>
          </a>
        </div>
        <h6>CONNECT ON LINKEDIN</h6>

      </div>
      <div class="col-xs-3">
          <div class="icon-border">
            <a href="#" class="icon-link">
              <div class="icon google-plus">
              </div>
            </a>
          </div>
        <h6>CONNECT ON GOOGLE+</h6>
      </div>

    </div>
  </div>
</div>
<div id="footer-end">
  <a href="#" class="footer-link">About</a>
  <a href="#" class="footer-link">Help</a>
  <a href="#" class="footer-link">Ask Questions</a>
  <a href="#" class="footer-link">Contact Us</a>
  <a href="#" class="footer-link">Blog</a>
</div> -->

<div class="expired-token-warning warning">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
  Fitbit access token has expired. Please log in again with Fitbit to view your data. If this is the guest account, Fitbit data is currently unavailable.
</div>

<div class="api-limit-warning warning">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
  Fitbit API request limit has been reached. Please until the start of the next hour.
</div>

<div class="api-limit-warning warning">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
  Fitbit API request limit has been reached. Please until the start of the next hour.
</div>


<%= render "signIn" %>
<%= render "signUp" %>
<%# render "movingNav" %>