config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/' => 'project#home', as: :root
  get '/about' => 'project#about', as: :about

  resources :stats, only: [:new, :index, :create]
  resources :users, only: [:new, :create]
  # resources :recipes
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  get '/guest_signin' => 'sessions#guest', as: :guest_signin

  resources :recipes, only: [:show, :index] do
    resources :foodlogs, only: [:create]
  end
  resources :foodlogs, only: [:destroy, :edit]
  get '/view_foodlogs' => 'foodlogs#show', as: :show_foodlog

  get '/auth/fitbit', as: :auth_fitbit
  post '/auth/fitbit' => 'callbacks#make_request', as: :fitbit_auth
  get '/auth/fitbit/callback' => 'callbacks#get_response'
  get '/weight' => 'callbacks#get_weight', as: :weight
  get '/add_weight' => 'callbacks#post_weight'

  namespace :api, defaults: {format: :json} do
      namespace :v1 do
        post '/authenticate_user' => 'users#login'
        post '/add_recipe' => 'recipes#add_recipe'
        get '/foodlogs' => 'recipes#show_foodlog'
        delete '/foodlogs' => 'recipes#delete_foodlog'
        get '/stats' => 'recipes#get_stats'
        resources :recipes, only: [:index]
      end
    end

end

app/models/foodlog.rb
class Foodlog < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/controllers/foodlogs_controller.rb
class FoodlogsController < ApplicationController
  def create
    @foodlog = Foodlog.new params.permit(:servings, :recipe_id)
    @foodlog.user = current_user
    get_stats
    respond_to do |format|
      if (@foodlog.servings * @foodlog.recipe.calories) > (@calorie_limit - @calories + 100)
        format.html { redirect_to recipes_path, alert: 'Calorie limit surpassed, please choose another meal' }
        format.js { render :add_failure }
      else
        if @foodlog.save
          get_stats
          format.html { redirect_to recipes_path }
          format.js { render :add_success }
        end
      end
    end
  end

  def destroy
    foodlog = Foodlog.find params[:id]
    foodlog.destroy
    respond_to do |format|
      get_stats
      format.html { redirect_to recipes_path }
      format.js { render :remove_success }
    end
  end

  def show
    if !params[:date].nil?
      @date = Date.parse(params[:date])
      @foodlog = current_user.foodlogs.where(created_at: @date.midnight..@date.end_of_day)
    else
      @date = Date.today
      @foodlog = current_user.foodlogs.where('created_at >= ?', Time.zone.now.beginning_of_day)
    end
    @calories = calories
  end

  def edit
  end

  private

  def calories
    total = 0
    @foodlog.each do |meal|
      total += (meal.servings * meal.recipe.calories)
    end
    total
  end

  def get_stats
    @calorie_limit = current_user.stats.last.calories
    @calories = daily_calories
    @carbs = carbs_calories
    @fats = fats_calories
    @proteins = proteins_calories
    @total = 1 + @carbs + @fats + @proteins
    gon.fats = @fats
    gon.carbs = @carbs
    gon.proteins = @proteins
  end
end

app/helpers/foodlogs_helper.rb
module FoodlogsHelper
end

app/views/foodlogs/_foodlog.html.erb
<div id="<%= dom_id(meal) %>" >
  <div class="row">
    <div class="col-md-4">
      <div class="">
        <h3><%= meal.recipe.name %></h3>
        <img src="<%= meal.recipe.photo %>" alt="" class="meal-plan-image" />
      </div>
      <%# link_to "Edit Servings", foodlog_path(meal), method: :delete, class: 'edit-meal-button meal-button' %>
      <%= link_to "Remove", foodlog_path(meal), method: :delete, remote: true, class: 'remove-meal-button meal-button' %>
    </div>
    <div class="col-md-8">
      <div class="col-xs-6">
        <h3>Ingredients</h3>
        <h5>(Makes <%= pluralize meal.recipe.servings, "serving" %>)</h5>
        <ul class="recipe-ingredients">
          <% meal.recipe.ingredients.split(",").each do |ingred| %>
          <li><%= ingred %></li>
          <% end %>
        </ul>
      </div>
      <div class="col-xs-6" class="recipe-wrapper">
        <h3>Cooking Directions</h3>
        <h5>(Makes <%= pluralize meal.recipe.servings, "serving" %>)</h5>
        <ol class='recipe-directions'>
          <% meal.recipe.directions.split("/").each do |direct| %>
          <li><%= direct %></li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
  <div class="row">
    <h3>I want to make <%= pluralize meal.servings, "serving" %> which will total <%= meal.servings * meal.recipe.calories %> calories</h3>
  </div>
  <hr>
</div>

app/views/foodlogs/add_failure.html.erb
$('#excess-calories').html(<%= @foodlog.servings * @foodlog.recipe.calories - (@calorie_limit - @calories) %>);
$('.alert').css('top', ($(window).height() * 0.4) + 'px');
$('.alert').css('left', ($(window).width() * 0.5) - (0.5 * $('.alert').width()) + 'px');
$('.alert').show();
setTimeout(function(){
  $('.alert').fadeOut('slow');
},5000)
 

app/views/foodlogs/add_success.html.erb
$("#meals").prepend("<%= j(render('/foodlogs/foodlog', {meal: @foodlog})) %>");

$("#calorie-bar").css('width', '<%= (@calories * 100 / @calorie_limit).round(1) %>%');
$("#fats-display").html('<%= (@fats * 100 / @total).round(1) %>%');
$("#carbs-display").html('<%= (@carbs * 100 / @total).round(1) %>%');
$("#proteins-display").html('<%= (@proteins * 100 / @total).round(1) %>%');
$("#calorie-display").html('<%= @calories %>');

app/views/foodlogs/add_success.js.erb
$("#meals").prepend("<%= j(render('/foodlogs/foodlog', {meal: @foodlog})) %>");

$("#calorie-bar").css('width', '<%= (@calories * 100 / @calorie_limit).round(1) %>%');
$("#fats-display").html('<%= (@fats * 100 / @total).round(1) %>%');
$("#carbs-display").html('<%= (@carbs * 100 / @total).round(1) %>%');
$("#proteins-display").html('<%= (@proteins * 100 / @total).round(1) %>%');
$("#calorie-display").html('<%= @calories %>');

app/views/foodlogs/remove_success.html.erb
$("#foodlog_<%= params[:id] %>").fadeOut('slow');
$("#calorie-bar").css('width', '<%= (@calories * 100 / @calorie_limit).round(1) %>%');
$("#fats-display").html('<%= (@fats * 100 / @total).round(1) %>%');
$("#carbs-display").html('<%= (@carbs * 100 / @total).round(1) %>%');
$("#proteins-display").html('<%= (@proteins * 100 / @total).round(1) %>%');
$("#calorie-display").html('<%= @calories %>');

app/views/foodlogs/remove_success.js.erb
$("#foodlog_<%= params[:id] %>").fadeOut('slow');
$("#calorie-bar").css('width', '<%= (@calories * 100 / @calorie_limit).round(1) %>%');
$("#fats-display").html('<%= (@fats * 100 / @total).round(1) %>%');
$("#carbs-display").html('<%= (@carbs * 100 / @total).round(1) %>%');
$("#proteins-display").html('<%= (@proteins * 100 / @total).round(1) %>%');
$("#calorie-display").html('<%= @calories %>');

app/views/foodlogs/show.html.erb
<div>
  <h1 style="color: white">View Foodlog History</h1>


  <div id="plan-area" class="row" >
    <h1>Select a date</h1>
    <%= form_tag show_foodlog_path, method: 'get' do %>
      <%# select_date Date.today, prefix: :start_date %>
      <div id="date-entry">
        <input type="date" name="date" value="<%= params[:date] %>" id="foodlog-date">
      </div>
      <%= submit_tag "Update", class: "btn btn-success", id: "date-update" %>
    <% end %>

    <% if @calories > 0 %>
      <h1>You ate <%= @calories %> calories on <%= @date %>.</h1>
    <% else %>
      <h1><%= @date %></h1>
    <% end %>
    <div id="foodlogs-history">
      <% if @foodlog.length > 0 %>
        <% @foodlog.each do |meal| %>
          <hr>
          <div class="row" style="width: 80%">
            <div class="col-md-8">
              <h1><%= meal.recipe.name %></h1>
              <h3><%= pluralize meal.servings, "serving" %>. <%= meal.servings * meal.recipe.calories %> calories.</h3>
            </div>
            <div class="col-md-4">
              <div class="">
                <img src="<%= meal.recipe.photo %>" alt="" class="foodlog-image" />
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <h1 style="margin-top: 50px;">No meals logged for this day</h1>
      <% end %>
    </div>
  </div>

</div>